---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ubuntu-palworld
  namespace: palworld
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ubuntu-palworld
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: ubuntu-palworld
    spec:
      nodeSelector:
        node-type: worker
      containers:
      - image: ubuntu
        name: ubuntu-palworld
        ports:
        - containerPort: 8055
          protocol: TCP
          name: ubuntu-palworld
        volumeMounts:
          - name: lv-storage
            mountPath: /data

      volumes:
        - name: lv-storage
          persistentVolumeClaim:
            claimName: ubuntu-palworld-pvc
