apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ubuntu-palworld
  namespace: palworld
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 64Gi
