apiVersion: v1
kind: Service
metadata:
  name: ubuntu-palworld
spec:
  selector:
    app: ubuntu-palworld
  type: LoadBalancer
  ports:
    - name: ubuntu-palworld-port
      protocol: TCP
      port: 8055
      targetPort: 8055
  loadBalancerIP: 192.168.68.221
