apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: palworld-server
  namespace: palworld
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 64Gi
