apiVersion: v1
kind: Service
metadata:
  name: palworld-server
spec:
  selector:
    app: palworld-server
  type: LoadBalancer
  ports:
    - name: palworld-port
      protocol: UDP
      port: 8211
      targetPort: 8211
  loadBalancerIP: 192.168.68.222
